services:
  api:
    image: caverntwo/summit-api
    ports:
      - "3456:3456"
    networks:
      - app-network
  web:
    image: caverntwo/summit-web
    ports:
      - "3457:3457"
    networks:
      - app-network
networks:
  app-network: {}